### ISSUE TITLE
"thor" dependency issue with Rails 6

### ISSUE THREAD

**Issue by dheeraj2dj** [codevise/activeadmin-searchable_select#19]
am unable to install this gem due to "thor" depedency version issue

**Comment by dheeraj2dj** [comment]
**UPDATE**
This helped with the installation - https://github.com/argerim/select2-rails/issues/194#issuecomment-571308643
Yet to evaluate usage

**Comment by tf** [comment]
As by your link, this is an issue with `select2-rails`. `activeadmin-searchable_select` [does not depend on `thor`](https://github.com/codevise/activeadmin-searchable_select/blob/bdfa4cc3f2d9103e193f339d3d753a8884ac254a/activeadmin-searchable_select.gemspec#L32). On `master`, `select2-rails` has [turned `thor` into a development dependency](https://github.com/argerim/select2-rails/commit/1c6f8fc5bca2d83aa5a9e9d487c7f54765ee3ffd). Apparently, the change has not been released yet as a gem, though. You should be able to bundle `select2-rails` via a `git` source in your `Gemfile`:

```
gem 'select2-rails', git: 'https://github.com/argerim/select2-rails'
```

Closing this issue since there is nothing that can be done in the context of this gem.
