### ISSUE TITLE
Pagination incorrect results

### ISSUE THREAD

**Issue by Yevhenii-Mohylskyi** [codevise/activeadmin-searchable_select#46]
I noticed a strange thing about the results being returned in the collection, not all of them were returned.
I started investigating the reason and noticed the following thing: Pagination returns page values in the parameters in the order 0, 2, 3...
The first API call does not include the page attribute in parameters. The second API call includes `params[:page] = 2`.
Accordingly, the following [code](https://github.com/codevise/activeadmin-searchable_select/blob/3e4130a5decb16b2114550e83308c5eae3d1a915/lib/activeadmin/searchable_select/option_collection.rb#L64) in the gem begins to return incorrect results.

page_index = 0;
per_page = 10;
We will select records from 0 to 10

page_index = 2;
per_page = 10;

We will select records from 20 to 30 and skip records from 10 to 20.

Not sure if this is a bug in the code or pagination gem versions or something else. Maybe you could help with that?

**Comment by davyhollevoet** [comment]
I noticed the same thing today: the second page is skipped.

Turns out that's because I also use [activeadmin_addons](https://github.com/platanus/activeadmin_addons), which re-initializes the select inputs. That means that the custom [ajax.data](https://github.com/codevise/activeadmin-searchable_select/blob/3e4130a5decb16b2114550e83308c5eae3d1a915/app/assets/javascripts/active_admin/searchable_select/init.js#L13C11-L13C15) is ignored and [pageParamWithBaseZero](https://github.com/codevise/activeadmin-searchable_select/blob/3e4130a5decb16b2114550e83308c5eae3d1a915/app/assets/javascripts/active_admin/searchable_select/init.js#L31) is not used to fix the offset.

My solution for now is to disable the select2ifying by activeadmin_addons:
```ruby
# config/initializers/active_admin_addons.rb
ActiveadminAddons.setup do |config|
  # Change to "default" if you want to use ActiveAdmin's default select control.
  config.default_select = 'default'
end
```

**Comment by Yevhenii-Mohylskyi** [comment]
@davyhollevoet Thanks for the advice, it works. But I think I found a better solution for this and it was my mistake. Just enough to import stylesheets and javascripts:

```
// active_admin.css.scss
@import "active_admin/searchable_select";
```

```
// active_admin.js
//= require active_admin/searchable_select
```
And now it works correctly.
